runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /(.*\.css)
  static_files: static/\1
  upload: static/.*\.css

- url: /
  script: login.php
  
- url: /BoredBear.php
  script: BoredBear.php
  
- url: /(.+\.php)$
  script: \1